Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,132 +3,126 @@ name: Publish releases
 on:
   release:
     types: [published]
+
 env:
   PYTHON_VERSION: "3.11"
 
 jobs:
   build-and-publish-pypi:
-    name: Builds and publishes releases to PyPI
+    name: Build and publish release to PyPI
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.vars.outputs.tag }}
+      version: ${{ steps.get-tag.outputs.tag }}
     steps:
-      - uses: actions/checkout@v4.1.4
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Get tag
-        id: vars
-        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
+        id: get-tag
+        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
+
       - name: Validate version number
-        run: >-
+        run: |
           if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
-            if ! [[ "${{ steps.vars.outputs.tag }}" =~ "b" ]]; then
-            echo "Pre-release: Tag is missing beta suffix (${{ steps.vars.outputs.tag }})"
+            if ! [[ "${{ steps.get-tag.outputs.tag }}" =~ "b" ]]; then
+              echo "Pre-release: Tag is missing beta suffix (${{ steps.get-tag.outputs.tag }})"
               exit 1
             fi
           else
-            if [[ "${{ steps.vars.outputs.tag }}" =~ "b" ]]; then
-              echo "Release: Tag must not have a beta suffix (${{ steps.vars.outputs.tag }})"
+            if [[ "${{ steps.get-tag.outputs.tag }}" =~ "b" ]]; then
+              echo "Release: Tag must not have a beta suffix (${{ steps.get-tag.outputs.tag }})"
               exit 1
             fi
           fi
+
       - name: Set up Python ${{ env.PYTHON_VERSION }}
-        uses: actions/setup-python@v5.1.0
+        uses: actions/setup-python@v2
         with:
           python-version: ${{ env.PYTHON_VERSION }}
-      - name: Install build
-        run: >-
-          pip install build tomli tomli-w
+
+      - name: Install build tools
+        run: pip install build tomli tomli-w
+
       - name: Set Python project version from tag
-        shell: python
-        run: |-
-          import tomli
-          import tomli_w
-
+        run: |
+          python3 -m pip install tomli tomli_w
+          python3 -c '
+          import tomli, tomli_w
           with open("pyproject.toml", "rb") as f:
-            pyproject = tomli.load(f)
-
-          pyproject["project"]["version"] = "${{ steps.vars.outputs.tag }}"
-
+              pyproject = tomli.load(f)
+          pyproject["project"]["version"] = "${{ steps.get-tag.outputs.tag }}"
           with open("pyproject.toml", "wb") as f:
-            tomli_w.dump(pyproject, f)
+              tomli_w.dump(pyproject, f)'
+
       - name: Build python package
-        run: >-
-          python3 -m build
+        run: python3 -m build
+
       - name: Publish release to PyPI
         uses: pypa/gh-action-pypi-publish@v1.9.0
         with:
           user: __token__
           password: ${{ secrets.PYPI_TOKEN }}
+
       - name: Wait for PyPI
         run: sleep 300
 
   build-and-push-container-image:
-    name: Builds and pushes the Music Assistant Server container to ghcr.io
+    name: Build and push Music Assistant Server container to ghcr.io
     runs-on: ubuntu-latest
     permissions:
       packages: write
     needs: build-and-publish-pypi
     steps:
-      - uses: actions/checkout@v4.1.4
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Download Widevine CDM client files from private repository
-        shell: bash
-        env:
-          TOKEN: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
         run: |
           mkdir -p widevine_cdm && cd widevine_cdm
-          curl -OJ -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/music-assistant/appvars/main/widevine_cdm_client/private_key.pem
-          curl -OJ -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/music-assistant/appvars/main/widevine_cdm_client/client_id.bin
-      - name: Log in to the GitHub container registry
-        uses: docker/login-action@v3.2.0
+          curl -OJ -H "Authorization: token ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}" https://raw.githubusercontent.com/music-assistant/appvars/main/widevine_cdm_client/private_key.pem
+          curl -OJ -H "Authorization: token ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}" https://raw.githubusercontent.com/music-assistant/appvars/main/widevine_cdm_client/client_id.bin
+
+      - name: Log in to the GitHub Container Registry
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.3.0
+        uses: docker/setup-buildx-action@v3
+
       - name: Version number for tags
         id: tags
-        shell: bash
-        run: |-
-          patch=${GITHUB_REF#refs/*/}
-          echo "patch=${patch}" >> $GITHUB_OUTPUT
-          echo "minor=${patch%.*}" >> $GITHUB_OUTPUT
-          echo "major=${patch%.*.*}" >> $GITHUB_OUTPUT
-      - name: Build and Push release
-        uses: docker/build-push-action@v6.2.0
-        if: github.event.release.prerelease == false
-        with:
-          context: .
-          platforms: linux/amd64,linux/arm64
-          file: Dockerfile
-          tags: |-
-            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.patch }},
-            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.minor }},
-            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.major }},
-            ghcr.io/${{ github.repository_owner }}/server:stable,
-            ghcr.io/${{ github.repository_owner }}/server:latest
-          push: true
-          build-args: "MASS_VERSION=${{ needs.build-and-publish-pypi.outputs.version }}"
-      - name: Build and Push pre-release
-        uses: docker/build-push-action@v6.2.0
-        if: github.event.release.prerelease == true
-        with:
-          context: .
-          platforms: linux/amd64,linux/arm64
-          file: Dockerfile
-          tags: |-
-            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.patch }},
-            ghcr.io/${{ github.repository_owner }}/server:beta
-          push: true
-          build-args: "MASS_VERSION=${{ needs.build-and-publish-pypi.outputs.version }}"
+        run: |
+          patch=${GITHUB_REF#refs/tags/}
+          echo "patch=${patch}" >> $GITHUB_ENV
+          echo "minor=${patch%.*}" >> $GITHUB_ENV
+          echo "major=${patch%.*.*}" >> $GITHUB_ENV
 
-          addon-version-update:
-    name: Updates the Addon repository with the new version
+      - name: Build and Push release
+        if: github.event.release.prerelease == 'false'
+        run: |
+          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/server:${{ env.major }} -t ghcr.io/${{ github.repository_owner }}/server:${{ env.minor }} -t ghcr.io/${{ github.repository_owner }}/server:${{ env.patch }} -t ghcr.io/${{ github.repository_owner }}/server:stable -t ghcr.io/${{ github.repository_owner }}/server:latest --push .
+
+  release-notes-update:
+    name: Update release notes and changelog
+    needs: [build-and-publish-pypi, build-and-push-container-image]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Update changelog and release notes
+        uses: xdumaster1/release-notes-merge-action@main
+        with:
+          github_token: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
+          release_tag: ${{ needs.build-and-publish-pypi.outputs.version }}
+          pre_release: ${{ github.event.release.prerelease }}
+
+  addon-version-update:
+    name: Update Addon repository with new version
     needs:
-      [
-        build-and-publish-pypi,
-        build-and-push-container-image,
-        release-notes-update,
-      ]
+      - build-and-publish-pypi
+      - build-and-push-container-image
+      - release-notes-update
     runs-on: ubuntu-latest
     steps:
       - name: Push new version number to addon config
